name: Insert Pokemon Cards

on:
  push:
    branches:
      - prod

jobs:
  insert-pokemon:
    runs-on: ubuntu-latest

    steps:
      - name: Run insert_pokemon.py via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/PokemonCardPictures/
            git pull origin prod
            echo "📦 Mise à jour du dépôt effectuée"
            python3 insert_pokemon.py
